language: perl
perl:
  - "5.30"
  - "5.10"
os: linux
dist: trusty
addons:
  apt:
    packages:
      - libsnmp-dev
      - phantomjs
      - graphviz
  hosts:
    - localhost
branches:
  only:
    - /^2\.\d{6}$/
    - 'master'
    - /.*travis.*/
install:
  - cpanm --quiet --notest https://github.com/egiles/test-compile/archive/v2.1.2.tar.gz PkgConfig Test::CChecker Alien::zlib::Static Alien::OpenSSL::Static Alien::SNMP
script: |
  perl Build.PL && \
  ./Build && \
  PERL_MM_USE_DEFAULT=1 ./Build installdeps --cpan_client 'cpanm --quiet --notest' && \
  ND_PHANTOMJS=/usr/bin/phantomjs ./Build test --test_files xt/
notifications:
  irc:
    on_success: always
    on_failure: always
    channels:
      - 'irc.libera.chat#netdisco'
#  email:
#    on_success: always
#    on_failure: always
#    recipients:
#      - 'netdisco-ng-commit@lists.sourceforge.net'
