language: perl
addons:
  apt:
    packages:
      - libsnmp-dev
      - phantomjs
branches:
  only:
    - /^2\.\d{6}$/
    - 'master'
install: true
script: |
  perl Build.PL && \
  ./Build && \
  PERL_MM_USE_DEFAULT=1 ./Build installdeps --cpan_client 'cpanm --quiet --notest' && \
  ND_PHANTOMJS=/usr/bin/phantomjs ./Build test --test_files xt/
notifications:
  irc:
    on_success: change
    on_failure: always
    channels:
      - 'chat.freenode.net#netdisco'
