language: perl
perl:
  - "5.30"
  - "5.10"
addons:
  apt:
    packages:
      - libsnmp-dev
      - phantomjs
      - graphviz 
  hosts:
    - localhost
branches:
  only:
    - /^2\.\d{6}$/
    - 'master'
install:
  - cpanm --quiet --notest PkgConfig Test::CChecker Alien::zlib::Static Alien::OpenSSL::Static Alien::SNMP
script: |
  perl Build.PL && \
  ./Build && \
  PERL_MM_USE_DEFAULT=1 ./Build installdeps --cpan_client 'cpanm --quiet --notest' && \
  ND_PHANTOMJS=/usr/bin/phantomjs ./Build test --test_files xt/
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
      - 'chat.freenode.net#netdisco'
#  email:
#    on_success: always
#    on_failure: always
#    recipients:
#      - 'netdisco-ng-commit@lists.sourceforge.net'
